projects
sashakboo/orpistudy pull request #1
Opened 2021-08-12 14:17 UTC by sashakboo

2021-08-18 12:49 UTC, gorodilov-directum commented
Не везде код оформлен по соглашениям. Дооформи плиз. Вообще можешь взять из репозитория Sungero файл `.editorconfig`, и закинуть его в папку с solution-ом. Тогда студия сама тебе будет показывать предупреждения, где в коде что не так.

2021-08-18 12:52 UTC, gorodilov-directum commented
3.	Базовая станция 3G:
    ●	Специальным образом регистрирует 3G-телефоны.
Надо как-то учесть это требование

2021-08-18 12:57 UTC, gorodilov-directum commented
Раз уж в курсе шла речь о событиях .net (event-ах, делегатах), давай заиспользуем их в задаче про телефоны. Например, для обработки исходящих вызовов базовой станцией

2021-08-18 13:31 UTC, gorodilov-directum commented on Telephony/Models/BaseStation.cs
> +    public BaseStation(int initialSize)
Здесь и далее: думаю это лишнее. Резервировать память для списков это какая-то преждевременная оптимизация

2021-08-18 13:31 UTC, gorodilov-directum commented on Telephony/Models/BaseStation.cs
> +      return phones.IndexOf(phone) > -1;
Здесь поиск в списке телефонов идёт по ссылке. Если в метод подсунуть другой объект Phone, с тем же номером и imei, то isRegistered вернёт false. Может реализовать в Phone проверку на Equals по Imei?

2021-08-18 13:31 UTC, gorodilov-directum commented on Telephony/Models/BaseStation.cs
> +  class BaseStation
Обычно явно указываем модификатор у классов: public или internal

2021-08-18 13:31 UTC, gorodilov-directum commented on Telephony/Models/Phone.cs
> +    private bool callInProgress = false;
Поля типа bool по дефолту инициализированы значением false, поэтому это лишнее

2021-08-18 13:31 UTC, gorodilov-directum commented on Telephony/Models/Phone.cs
> +    public IList<Contact> Contacts { get; set; }
Если наружу у объекта торчит коллекция, как здесь, то обычно не даём возможности её означивать снаружи (оставляем только getter).

2021-08-18 13:31 UTC, gorodilov-directum commented on Telephony/Models/PhoneNumber.cs
> +    public string CountryCode { get; private set; }
В современной версии языка если свойства означиваются только в конструкторе, то `private set` для них можно не писать

2021-08-18 13:31 UTC, gorodilov-directum commented on Classes/Program.cs
> +      if (type1.Equals(type2))
Типы можно (и нужно) сравнивать по ссылке (`type1 ==type2`): они доступны только в единственном экземпляре.

2021-08-18 13:31 UTC, gorodilov-directum commented on Classes/Program.cs
> +      if (type1.BaseType.Equals(type2))
Признак того, что класс унаследован от другого класса, нужно проверять не так. Есть специальные методы `IsAssignableFrom`, `IsSubclassOf`. У тебя же для иерархии наследования A->B->C для типа C скажет, что он не наследник A, хотя это не так.

2021-08-18 13:31 UTC, gorodilov-directum commented on Classes/Program.cs
> +    static string ClassRelations<T1, T2>(T1 obj1, T2 obj2)
Здесь обобщение не работает - все объекты на входе типа `object`. Так что лучше его убрать. А если делать обобщения, то объекты в параметрах вообще можно не передавать, т.к. тип можно получить из параметра типа, например, `typeof(T1)`

2021-08-18 13:31 UTC, gorodilov-directum commented on WorkWithExcel/Program.cs
> +    static void ExportToExcel(List<Product> products, string path)
Полученную таблицу Excel необходимо отобразить.

Надо реализовать требование

2021-08-18 13:31 UTC, gorodilov-directum commented on WorkWithExcel/Program.cs
> +      Marshal.ReleaseComObject(excel);
Насколько я помню, CLR сама справляется с освобождением ссылок на COM-объекты, поэтому явно релизить их не надо

2021-08-18 13:31 UTC, gorodilov-directum requested changes
Поправь пж по замечаниям

2021-08-18 13:54 UTC, sashakboo commented on Telephony/Models/BaseStation.cs
> +    public BaseStation(int initialSize)
По идее не для резервирования памяти, а для ограничения количества телефонов, которые может обслуживать станция. Но да, думаю это лишнее усложение.

2021-08-19 06:36 UTC, gorodilov-directum commented on Telephony/Models/BaseStation.cs
> +    public BaseStation(int initialSize)
Этот параметр initialSize в конструкторе списка означает, для скольких элементов резервировать память (https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.-ctor?view=net-5.0#System_Collections_Generic_List_1__ctor_System_Int32_). Когда добавляешь элементы в список, он динамически увеличивается. И вот иногда если заранее известно будущее количество элементов, оптимизируют, и задают начальную ёмкость, чтобы лишний раз не перераспределять память.

2021-08-19 08:41 UTC, sashakboo commented on Telephony/Models/BaseStation.cs
> +      return phones.IndexOf(phone) > -1;
Переопределил Equals в классе Phone

2021-08-19 08:44 UTC, sashakboo commented on Telephony/Models/BaseStation.cs
> +    public BaseStation(int initialSize)
Убрал

2021-08-19 08:44 UTC, sashakboo commented on Telephony/Models/BaseStation.cs
> +  class BaseStation
Поправил

2021-08-19 08:45 UTC, sashakboo commented on Telephony/Models/Phone.cs
> +    public IList<Contact> Contacts { get; set; }
Поправил

2021-08-19 08:45 UTC, sashakboo commented on Classes/Program.cs
> +      if (type1.Equals(type2))
Поправил

2021-08-19 08:45 UTC, sashakboo commented on Classes/Program.cs
> +    static string ClassRelations<T1, T2>(T1 obj1, T2 obj2)
Поправил

2021-08-19 08:45 UTC, sashakboo commented on WorkWithExcel/Program.cs
> +    static void ExportToExcel(List<Product> products, string path)
Сделал только отображение таблицы

2021-08-19 08:45 UTC, sashakboo commented on WorkWithExcel/Program.cs
> +      Marshal.ReleaseComObject(excel);
Без этого не завершался процесс Excel, пока я не закрывал свое приложение.

2021-08-19 08:47 UTC, sashakboo commented on Telephony/Models/BaseStation.cs
> +  class BaseStation
Поправил

2021-08-20 12:56 UTC, gorodilov-directum commented on Classes/Program.cs
> +      return string.Empty;
Небольшое замечание по поводу использования linq. Если нужно использовать результаты запроса многократно, как например, здесь `commonAncestor`, лучше их сохранить в список или массив. Иначе при каждом обращении к `commonAncestor` будет перебираться итератор `GetAncestors`. Это так, к слову об оптимизации.

2021-08-20 12:57 UTC, gorodilov-directum approved these changes

2021-08-25 06:20 UTC, merged